In [9]:
import random
import numpy as np
import pandas as pd

# Loss Function in Logistic Regression

## Random Variable

A coin toss is a random variable. We cannot possibly predict the result of the coin toss with certainty.

## 0) What are possible events of one coin toss?

- Head
- Tails

## 1) What is a fair coin?

If the probability of observing either event of a coin toss is 50%.

$P(Heads) = p = 0.5$<br>
$P(Tails) = 1-p = 0.5$

## 2) What is the probability of observing Heads when you toss a fair coin?

P(Kopf) = p = 0.5

The coin toss follows a **Bernoulli Distribution**. The **Bernoulli Distribution** is a probability distribution for random variables with two possible events.

Heads: y = 1 (like Survived = 1)<br>
Tails: y = 0 (like Survived = 0)

$$
P(y) = \begin{cases} p &\mbox{if } y = 1 \\
   1-p & \mbox{if } y = 0
   \end{cases}
$$

or (equivalently)

$$
P(y) = p^y * (1-p)^{1-y}
$$

## 3) What is the probability of observing the sequence of events (*Heads*, *Heads*) if a coin is tossed twice?

$$
P(Heads, Heads) = p * p = 0.25
$$

Equivalently it could be written as

$$
P(Heads, Heads) = P(Heads) * P(Heads)
$$

or as

$$
P(Heads, Heads) = (p^{y_1} * (1-p)^{1-y_1}) * (p^{y_2} * (1-p)^{1-y_2})
$$

oder 

$$
P(Heads, Heads) = \prod_{i=1}^2 p^{y_i} * (1-p)^{1-y_i}
$$

--> **The probability of observing a sequence of events can be written as the product of individual probabilities of bernoulli distributed random variables.**

Generally:

$$
P(y_1,...,y_n) = \prod_{i=1}^N p^{y_i} * (1-p)^{1-y_i}
$$

## 4) Let's turn around the question

**So far**: If we know *p*, what is the probability of observing a certain sequence of events?

**New**: If we observe a certain sequence of events in the real world, what does that tell us about *p*?

If we observe the sequence 

- Heads, Heads, Heads, Tails

and we do not know whether our coin is fair or not, what can we say about *p*?

- We will never know with certainty!!!
- Our best guess of what *p* is, is the value for which P(Heads, Heads, Heads, Tails) is highest.

We turn the probability of the sequence occuring under p

$$
P(Kopf, Kopf, Kopf, Zahl) = \prod_{i=1}^4 p^y_i * (1-p)^{1-y_i} = p * p * p * (1-p)
$$

into a likelihood-function of an estimate of *p* - *$\hat{p}$*

$$
L(\hat{p}) = \prod_{i=1}^4 \hat{p}^y_i * (1-\hat{p})^{1-y_i} = \hat{p} * \hat{p} * \hat{p} * (1-\hat{p})
$$

In [14]:
def calculate_likelihoods(p_hat, sequence):
    '''
    Calculates the likelihood of observing a sequence of
    independent Bernoulli trial.
    
    Params:
    -------
    
    p_hat:    Estimate of p
    sequence: Observed sequence of events
    '''
    return (p_hat**np.array(sequence) * (1-p_hat)**(1-np.array(sequence))).prod()

In [15]:
np.linspace(0, 1, 9)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

In [16]:
# Werte für p die wir ausprobieren wollen
probabilities = np.linspace(0, 1, 9)

# H, H, H, T
sequence = [1, 1, 1, 0]

In [18]:
# Find the best value for p
for probability in probabilities:
    print(f'The likelihood of observing the sequence {sequence} if p is {probability} \
is {round(calculate_likelihoods(probability, sequence), 3)}')

The likelihood of observing the sequence [1, 1, 1, 0] if p is 0.0 is 0.0
The likelihood of observing the sequence [1, 1, 1, 0] if p is 0.125 is 0.002
The likelihood of observing the sequence [1, 1, 1, 0] if p is 0.25 is 0.012
The likelihood of observing the sequence [1, 1, 1, 0] if p is 0.375 is 0.033
The likelihood of observing the sequence [1, 1, 1, 0] if p is 0.5 is 0.062
The likelihood of observing the sequence [1, 1, 1, 0] if p is 0.625 is 0.092
The likelihood of observing the sequence [1, 1, 1, 0] if p is 0.75 is 0.105
The likelihood of observing the sequence [1, 1, 1, 0] if p is 0.875 is 0.084
The likelihood of observing the sequence [1, 1, 1, 0] if p is 1.0 is 0.0


## 5) Which probability are we interested in in the Titanic project?

What are the events?<br>
**Events**: Survived, Died

P(Survived) = p<br>
P(Died) = 1-p

## 6) We are more interested in conditional probabilities

P(Survived|Age,Sex,Pclass) = p<br>
P(Died|Age,Sex,Pclass) = 1-p

## 7) The probabilities have to be estimated for all possible combinations of X

--> That is what the sigmoid function does.<br>
--> The coefficients $b, w_1, w_2,...,w_n$ are estimated such that the likelihood is maximized.

$$
\hat{p} = \frac{1}{1+e^{-(b + w_1*Age + w_2*Sex + w_3*Pclass)}}
$$

## 8) Likelihood Function

$$
L(\hat{p}) = \prod_{i=1}^N \hat{p}^{y_i} * (1-\hat{p})^{1-y_i}
$$

## 9) Log-Likelihood Function

Mathematical optimization is easier if a function is additive.

- Taking the logarithm turns the product into a sum.
- The parameters that maximize a function are the same as the parameters that maximize the logarithm of the function.

$$
log(L(\hat{p})) = \sum_{i=1}^N y_i * log(\hat{p}) + (1-y_i) * log((1-\hat{p}))
$$

## 10) Loss Function

The loss function is just the negative log-likelihood function.

Maximizing a function is the same as minimizing its negative transformation.

$$
Loss = -log(L(\hat{p})) = - \sum_{i=1}^N y_i * log(\hat{p}) + (1-y_i) * log((1-\hat{p}))
$$

Logistic Regression maximizes the likelihood of the observed sequence to occur by tweaking its parameters

In [19]:
def log_loss_own(p_hat, sequence):
    '''
    Calculates the overall probability of observing a sequence of independent
    independent Bernoulli trial.
    
    Params:
    -------
    
    p_hat:    Estimate of p
    sequence: Observed sequence of events
    '''
    return - (np.log(p_hat)*np.array(sequence) + np.log((1-p_hat))*(1-np.array(sequence))).sum()

In [20]:
# Let us import the titanic data
df = pd.read_csv('train.csv', index_col=0)
df.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

#### At this point you would go through the following steps:
- Assign X and y and train_test_split
- EDA
- Feature Engineering
- Training our model

In [21]:
X = df[['Pclass']]
y = df['Survived']

In [22]:
# Fit a model
from sklearn.linear_model import LogisticRegression

In [23]:
m = LogisticRegression()

In [24]:
m.fit(X, y)

LogisticRegression()

In [25]:
# w: slope
m.coef_

array([[-0.84371207]])

In [26]:
# b: position at x=0
m.intercept_

array([1.43255005])

In [27]:
# Let us have a look at the loss
from sklearn.metrics import log_loss

In [30]:
# prediction vs. probability prediction
# we ultimately are interested in m.predict(X) because it answers our question of 
# who survives and who doesn't

# The model optimizes on m.predict_proba(X); these are the probabilitie estimates
m.predict_proba(X) # [probability_of_dying, probability_of_surviving] for each passenger

array([[0.7499951 , 0.2500049 ],
       [0.35690152, 0.64309848],
       [0.7499951 , 0.2500049 ],
       ...,
       [0.7499951 , 0.2500049 ],
       [0.35690152, 0.64309848],
       [0.7499951 , 0.2500049 ]])

In [42]:
len(m.predict_proba(X)) # We have one prediction per passenger

891

In [31]:
log_loss(y, m.predict_proba(X))
# m.fit() will tweak our parameters b and w in order to minimize this log_loss
# So if we calculated the log_loss with any other parameters, it will be bigger

0.6085336468537561

In [32]:
# define sigmoid function
def sigmoid(x, b, w):
    return 1/(1+np.exp(-(b+x*w)))

In [33]:
b = m.intercept_[0]
b

1.4325500494239256

In [35]:
w = m.coef_[0][0]
w

-0.8437120730506076

In [39]:
Pclass = 3

In [40]:
# Calculate the probability of survival of a member of Pclass 1
sigmoid(Pclass, b, w)

0.2500048973332678